### ISSUE TITLE
issue with connecting to my remote mongo server

### ISSUE THREAD

**Issue by shahidammer** [eamonnmcevoy/go_rest_api#1]
I am running your application and i am getting this strange error

> `panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1195109]
> 
> goroutine 1 [running]:
> go_rest_api/pkg/mongo.(*Session).Open(0x0, 0x0, 0x137d36f)
> 	/Users/shahidammer/.gvm/pkgsets/go1.9.2/global/src/go_rest_api/pkg/mongo/session.go:22 +0x149
> main.(*App).Initialize(0xc420055f60)
> 	/Users/shahidammer/.gvm/pkgsets/go1.9.2/global/src/go_rest_api/cmd/app/app.go:16 +0x33
> main.main()
> 	/Users/shahidammer/.gvm/pkgsets/go1.9.2/global/src/go_rest_api/cmd/app/app.go:31 +0x3d`

I have replaced the uri of mongo db from localhost to remote. Help!!

**Comment by eamonnmcevoy** [comment]
Can you run it with a local mongo connection?

**Comment by shahidammer** [comment]
No i can not

**Comment by shahidammer** [comment]
The problem is with this line

> 	s.session, err = mgo.Dial("mongodb://172.25.33.205:27017")
> 	if err != nil {
> 		return err
> 	}

if i replace the s.session with any other var name then it works
i.e.

> Xsession, err = mgo.Dial("mongodb://172.25.33.205:27017")
> 	if err != nil {
> 		return err
> 	}

but when i do this 

> s.session = Xsession


i get the panic runtime error

**Comment by eamonnmcevoy** [comment]
Apologies, I need to push an update to the repo, please update your code as the sample here in my medium article: https://hackernoon.com/make-yourself-a-go-web-server-with-mongodb-go-on-go-on-go-on-48f394f24e


```
package mongo

import (
  "gopkg.in/mgo.v2"
)

type Session struct {
  session *mgo.Session
}

func NewSession(url string) (*Session,error) {
  session, err := mgo.Dial("localhost:27017")
  if err != nil {
    return nil,err
  }
  return &Session{session}, err
}

func(s *Session) Copy() *Session {
  return &Session{s.session.Copy()}
}

func(s *Session) GetCollection(db string, col string) *mgo.Collection {
  return s.session.DB(db).C(col)
}

func(s *Session) Close() {
  if(s.session != nil) {
    s.session.Close()
  }
}
```


```
package main

import (
	"go_web_server/pkg/crypto"
	"go_web_server/pkg/mongo"
	"go_web_server/pkg/server"
	"log"
)

func main() {
	ms, err := mongo.NewSession("127.0.0.1:27017")
	if err != nil {
		log.Fatalln("unable to connect to mongodb")
	}
	defer ms.Close()

	h := crypto.Hash{}
	u := mongo.NewUserService(ms.Copy(), "go_web_server", "user", &h)
	s := server.NewServer(u)

	s.Start()
}
```

**Comment by eamonnmcevoy** [comment]
I've updated the code if you are still working with this.
